apiVersion: v1
kind: Pod
metadata:
  name: liquibase-init-app-pod
  labels:
    app: liquibase-init-app
spec:
  containers:
  - name: timecard
    image: 127.0.0.1:32701/timecard:1.0.24
  initContainers:
  - name: liquibase-init
    image: 127.0.0.1:32701/liquibase-init:1.0.18