apiVersion: v1
kind: Service
metadata:
  name: {{ include "callisto.fullname" . }}
  labels:
    {{- include "callisto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      {{- if eq "NodePort" .Values.service.type }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "callisto.selectorLabels" . | nindent 4 }}
